name: aoc2021

dependencies:
  - base >= 4.7 && < 5
  - split
  - containers
  - mtl

library:
  source-dirs: src

executables:
  solve:
    main:           Main.hs
    source-dirs:    app
    dependencies:
      - aoc2021
      - bytestring
      - directory
      - http-client
      - http-client-tls
      - http-types


